steps:
  # Build the container image from repo root
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/sentinal-repo/sentinal-web:$BUILD_ID'
      - '-f'
      - 'packages/web/Dockerfile'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://sentinal-api-711220270423.asia-south1.run.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_WORKER_URL=https://sentinal-worker-711220270423.asia-south1.run.app'
      - '.'
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/sentinal-repo/sentinal-web:$BUILD_ID']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sentinal-web'
      - '--image'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/sentinal-repo/sentinal-web:$BUILD_ID'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_PUBLIC_API_URL=https://sentinal-api-711220270423.asia-south1.run.app,NEXT_PUBLIC_WORKER_URL=https://sentinal-worker-711220270423.asia-south1.run.app'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/sentinal-repo/sentinal-web:$BUILD_ID'

timeout: '1200s'
