steps:
  # Build the container image from repo root
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sentinal-web:$BUILD_ID'
      - '-f'
      - 'packages/web/Dockerfile'
      - '.'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sentinal-web:$BUILD_ID']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sentinal-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sentinal-web:$BUILD_ID'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'
      - '--min-instances'
      - '0'
      - '--port'
      - '3001'
      - '--set-env-vars'
      - 'NODE_ENV=production'

images:
  - 'gcr.io/$PROJECT_ID/sentinal-web:$BUILD_ID'

timeout: '1200s'
